"""balance table - description

Revision ID: 08e44e512d5b
Revises: 3e5bbecfe077
Create Date: 2020-02-13 19:20:08.865761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e44e512d5b'
down_revision = '3e5bbecfe077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('description', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance', 'description')
    # ### end Alembic commands ###
